service: liquidfan-deployer
provider:
  name: aws
  runtime: nodejs8.10
functions:
  trigger:
    handler: index.trigger
    events:
    - schedule:
        rate: cron(*/15 * * * ? *)
        enabled: true
